org.gradle.jvmargs=-Xmx2G
loom.platform=neoforge

minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
yarn_mappings_patch=1.21+build.6
neoforge_version=21.1.248

mod_base_version=1.2.7
mod_version_meta=1.21.1.neoforge
maven_group=com.red.masaadditions
archives_base_name=MasaAdditions

mafglib_version=0.4.3+mc1.21.1
forgematica_version=0.4.1+mc1.21.1
tweakerge_version=0.4.3+mc1.21.1
bocchud_version=0.4.1+mc1.21.1
